### ISSUE TITLE
Enable lexical binding

### ISSUE THREAD

**Issue by progfolio** [trev-dev/tangonov-theme#4]
tangonov-theme.el does not have lexical binding enabled.
I'm surprised the MELPA review didn't catch this.

**Comment by trev-dev** [comment]
Thanks progfolio. Is there some reason lexical bind is required?

**Comment by progfolio** [comment]
Take a look at https://www.gnu.org/software/emacs/manual/html_node/elisp/Lexical-Binding.html for several reasons.

**Comment by trev-dev** [comment]
You had me at "opportunity for optimizations". I'll get this done
